[book]
title = "Responsible Play"
authors = ["Logan KingðŸ‘‘"]
description = "Explode Your Pleasure, Not Your Life. A framework for navigating mistakes, power, and repair in intimate spaces."
language = "en"

[build]
build-dir = "docs"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/sloganking/sexy-minesweeper"
